version: '3'
services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: billbudyUser
      POSTGRES_PASSWORD: billbudy
      POSTGRES_DB: billbudy
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "3002:5432"
    container_name: billbudy_db
    volumes:
      - gestion_db_data:/var/lib/postgresql/data

  api:
    build: ./api
    ports:
      - "3001:3001"
    container_name: billbudy_api
    depends_on:
      - db
    restart: on-failure

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 3003:8080

volumes:
  gestion_db_data:
    name: gestion_db_data