GET http://localhost:3001/groups/2/members
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWd1c3RpbiIsImxhc3RuYW1lIjoiQ29sbWFuIiwidXNlcm5hbWUiOiJhZ3VzdGluY29sbWFuIiwiaWF0IjoxNzE2MjQ3MjIwLCJleHAiOjE3MTYyNTA4MjB9.qdqHzrqChYzUl96JKg861vgBgUCDJ0LD1aTHC5jY3vc